export interface EmojiItem {
  name: string
  index: number
  path: string
  asset: any
}

export const EmojiList: EmojiItem[] = [
  {
    name: '[/微笑]',
    index: 0,
    path: 'weixiao.png',
    asset: './weixiao.png',
  },
  { name: '[/色]', index: 1, path: 'aimu.png', asset: './aimu.png' },
  {
    name: '[/发呆]',
    index: 2,
    path: 'liangdai.png',
    asset: './liangdai.png',
  },
  {
    name: '[/酷拽]',
    index: 3,
    path: 'kuye.png',
    asset: './kuye.png',
  },
  {
    name: '[/抠鼻]',
    index: 4,
    path: 'koubi.png',
    asset: './koubi.png',
  },
  {
    name: '[/流泪]',
    index: 5,
    path: 'liulei.png',
    asset: './liulei.png',
  },
  {
    name: '[/捂脸]',
    index: 6,
    path: 'wulian.png',
    asset: './wulian.png',
  },
  {
    name: '[/发怒]',
    index: 7,
    path: 'fanu.png',
    asset: './fanu.png',
  },
  {
    name: '[/呲牙]',
    index: 8,
    path: 'ziya.png',
    asset: './ziya.png',
  },
  {
    name: '[/一起加油]',
    index: 9,
    path: 'yiqijiayou.png',
    asset: './yiqijiayou.png',
  },
  {
    name: '[/害羞]',
    index: 10,
    path: 'haixiu.png',
    asset: './haixiu.png',
  },
  {
    name: '[/调皮]',
    index: 11,
    path: 'keai.png',
    asset: './keai.png',
  },
  { name: '[/晕]', index: 12, path: 'yun.png', asset: './yun.png' },
  {
    name: '[/衰]',
    index: 13,
    path: 'shuai.png',
    asset: './shuai.png',
  },
  {
    name: '[/闭嘴]',
    index: 14,
    path: 'bizui.png',
    asset: './bizui.png',
  },
  {
    name: '[/机智]',
    index: 15,
    path: 'jizhi.png',
    asset: './jizhi.png',
  },
  { name: '[/赞]', index: 16, path: 'zan.png', asset: './zan.png' },
  {
    name: '[/鼓掌]',
    index: 17,
    path: 'guzhang.png',
    asset: './guzhang.png',
  },
  {
    name: '[/感谢]',
    index: 18,
    path: 'qidao.png',
    asset: './qidao.png',
  },
  {
    name: '[/抱抱你]',
    index: 19,
    path: 'baobaoni.png',
    asset: './baobaoni.png',
  },
  {
    name: '[/来看我]',
    index: 20,
    path: 'laikanwo.png',
    asset: './laikanwo.png',
  },
  {
    name: '[/灵机一动]',
    index: 21,
    path: 'lingguangyishan.png',
    asset: './lingguangyishan.png',
  },
  { name: '[/耶]', index: 22, path: 'ye.png', asset: './ye.png' },
  {
    name: '[/打脸]',
    index: 23,
    path: 'dalian.png',
    asset: './dalian.png',
  },
  {
    name: '[/大笑]',
    index: 24,
    path: 'daxiao.png',
    asset: './daxiao.png',
  },
  {
    name: '[/哈欠]',
    index: 25,
    path: 'haqian.png',
    asset: './haqian.png',
  },
  {
    name: '[/震惊]',
    index: 26,
    path: 'zhenliang.png',
    asset: './zhenliang.png',
  },
  {
    name: '[/送心]',
    index: 27,
    path: 'songxin.png',
    asset: './songxin.png',
  },
  { name: '[/困]', index: 28, path: 'kun.png', asset: './kun.png' },
  {
    name: '[/疑问]',
    index: 29,
    path: 'what.png',
    asset: './what.png',
  },
  {
    name: '[/泣不成声]',
    index: 30,
    path: 'qibuchengsheng.png',
    asset: './qibuchengsheng.png',
  },
  {
    name: '[/小鼓掌]',
    index: 31,
    path: 'xiaoguzhang.png',
    asset: './xiaoguzhang.png',
  },
  {
    name: '[/大金牙]',
    index: 32,
    path: 'dajinya.png',
    asset: './dajinya.png',
  },
  {
    name: '[/偷笑]',
    index: 33,
    path: 'touxiao.png',
    asset: './touxiao.png',
  },
  {
    name: '[/石化]',
    index: 34,
    path: 'shihua.png',
    asset: './shihua.png',
  },
  {
    name: '[/思考]',
    index: 35,
    path: 'sikao.png',
    asset: './sikao.png',
  },
  {
    name: '[/吐血]',
    index: 36,
    path: 'tuxie.png',
    asset: './tuxie.png',
  },
  {
    name: '[/可怜]',
    index: 37,
    path: 'kelian.png',
    asset: './kelian.png',
  },
  { name: '[/嘘]', index: 38, path: 'xu.png', asset: './xu.png' },
  {
    name: '[/撇嘴]',
    index: 39,
    path: 'piezui.png',
    asset: './piezui.png',
  },
  {
    name: '[/笑哭]',
    index: 40,
    path: 'xiaoku.png',
    asset: './xiaoku.png',
  },
  {
    name: '[/奸笑]',
    index: 41,
    path: 'jianxiao.png',
    asset: './jianxiao.png',
  },
  {
    name: '[/得意]',
    index: 42,
    path: 'deyi.png',
    asset: './deyi.png',
  },
  {
    name: '[/憨笑]',
    index: 43,
    path: 'hanxiao.png',
    asset: './hanxiao.png',
  },
  {
    name: '[/坏笑]',
    index: 44,
    path: 'huaixiao.png',
    asset: './huaixiao.png',
  },
  {
    name: '[/抓狂]',
    index: 45,
    path: 'zhuakuang.png',
    asset: './zhuakuang.png',
  },
  {
    name: '[/泪奔]',
    index: 46,
    path: 'leiben.png',
    asset: './leiben.png',
  },
  { name: '[/钱]', index: 47, path: 'qian.png', asset: './qian.png' },
  {
    name: '[/恐惧]',
    index: 48,
    path: 'kongju.png',
    asset: './kongju.png',
  },
  {
    name: '[/愉快]',
    index: 49,
    path: 'xiao.png',
    asset: './xiao.png',
  },
  {
    name: '[/快哭了]',
    index: 50,
    path: 'kuaikule.png',
    asset: './kuaikule.png',
  },
  {
    name: '[/翻白眼]',
    index: 51,
    path: 'fanbaiyan.png',
    asset: './fanbaiyan.png',
  },
  {
    name: '[/互粉]',
    index: 52,
    path: 'hufen.png',
    asset: './hufen.png',
  },
  {
    name: '[/我想静静]',
    index: 53,
    path: 'woxiangjingjing.png',
    asset: './woxiangjingjing.png',
  },
  {
    name: '[/委屈]',
    index: 54,
    path: 'weiqu.png',
    asset: './weiqu.png',
  },
  {
    name: '[/舔屏]',
    index: 55,
    path: 'tianping.png',
    asset: './tianping.png',
  },
  {
    name: '[/鄙视]',
    index: 56,
    path: 'bishi.png',
    asset: './bishi.png',
  },
  {
    name: '[/飞吻]',
    index: 57,
    path: 'feiwen.png',
    asset: './feiwen.png',
  },
  {
    name: '[/再见]',
    index: 58,
    path: 'zaijian.png',
    asset: './zaijian.png',
  },
  {
    name: '[/紫薇别走]',
    index: 59,
    path: 'ziweibiezou.png',
    asset: './ziweibiezou.png',
  },
  {
    name: '[/听歌]',
    index: 60,
    path: 'tingge.png',
    asset: './tingge.png',
  },
  {
    name: '[/求抱抱]',
    index: 61,
    path: 'qiubaobao.png',
    asset: './qiubaobao.png',
  },
  {
    name: '[/绝望的凝视]',
    index: 62,
    path: 'zhoudongyudeningshi.png',
    asset: './zhoudongyudeningshi.png',
  },
  {
    name: '[/不失礼貌的微笑]',
    index: 63,
    path: 'masichundeweixiao.png',
    asset: './masichundeweixiao.png',
  },
  {
    name: '[/不看]',
    index: 64,
    path: 'bukan.png',
    asset: './bukan.png',
  },
  {
    name: '[/裂开]',
    index: 65,
    path: 'liekai.png',
    asset: './liekai.png',
  },
  {
    name: '[/干饭人]',
    index: 66,
    path: 'ganfanren.png',
    asset: './ganfanren.png',
  },
  {
    name: '[/吐舌]',
    index: 67,
    path: 'tushe.png',
    asset: './tushe.png',
  },
  {
    name: '[/呆无辜]',
    index: 68,
    path: 'daiwugu.png',
    asset: './daiwugu.png',
  },
  { name: '[/看]', index: 69, path: 'kan.png', asset: './kan.png' },
  {
    name: '[/白眼]',
    index: 70,
    path: 'baiyan.png',
    asset: './baiyan.png',
  },
  {
    name: '[/熊吉]',
    index: 71,
    path: 'xiongji.png',
    asset: './xiongji.png',
  },
  {
    name: '[/猪头]',
    index: 72,
    path: 'zhutou.png',
    asset: './zhutou.png',
  },
  {
    name: '[/冷漠]',
    index: 73,
    path: 'lengmo.png',
    asset: './lengmo.png',
  },
  {
    name: '[/微笑袋鼠]',
    index: 74,
    path: 'weixiaodaishu.png',
    asset: './weixiaodaishu.png',
  },
  {
    name: '[/凝视]',
    index: 75,
    path: 'ningshi.png',
    asset: './ningshi.png',
  },
  {
    name: '[/暗中观察]',
    index: 76,
    path: 'anzhongguancha.png',
    asset: './anzhongguancha.png',
  },
  {
    name: '[/二哈]',
    index: 77,
    path: 'erha.png',
    asset: './erha.png',
  },
  {
    name: '[/菜狗]',
    index: 78,
    path: 'caigou.png',
    asset: './caigou.png',
  },
  {
    name: '[/黑脸]',
    index: 79,
    path: 'heilian.png',
    asset: './heilian.png',
  },
  {
    name: '[/吃瓜群众]',
    index: 80,
    path: 'chiguaqunzhong.png',
    asset: './chiguaqunzhong.png',
  },
  {
    name: '[/绿帽子]',
    index: 81,
    path: 'lvmaozi.png',
    asset: './lvmaozi.png',
  },
  {
    name: '[/摸头]',
    index: 82,
    path: 'motou.png',
    asset: './motou.png',
  },
  {
    name: '[/皱眉]',
    index: 83,
    path: 'zhoumei.png',
    asset: './zhoumei.png',
  },
  {
    name: '[/擦汗]',
    index: 84,
    path: 'cahan.png',
    asset: './cahan.png',
  },
  {
    name: '[/红脸]',
    index: 85,
    path: 'honglian.png',
    asset: './honglian.png',
  },
  {
    name: '[/尬笑]',
    index: 86,
    path: 'gaxiao.png',
    asset: './gaxiao.png',
  },
  {
    name: '[/做鬼脸]',
    index: 87,
    path: 'zuoguilian.png',
    asset: './zuoguilian.png',
  },
  {
    name: '[/强]',
    index: 88,
    path: 'qiang.png',
    asset: './qiang.png',
  },
  {
    name: '[/如花]',
    index: 89,
    path: 'ruhua.png',
    asset: './ruhua.png',
  },
  { name: '[/吐]', index: 90, path: 'tu.png', asset: './tu.png' },
  {
    name: '[/惊喜]',
    index: 91,
    path: 'liangxi.png',
    asset: './liangxi.png',
  },
  {
    name: '[/敲打]',
    index: 92,
    path: 'qiaoda.png',
    asset: './qiaoda.png',
  },
  {
    name: '[/奋斗]',
    index: 93,
    path: 'fendou.png',
    asset: './fendou.png',
  },
  {
    name: '[/吐彩虹]',
    index: 94,
    path: 'tucaihong.png',
    asset: './tucaihong.png',
  },
  {
    name: '[/大哭]',
    index: 95,
    path: 'daku.png',
    asset: './daku.png',
  },
  {
    name: '[/嘿哈]',
    index: 96,
    path: 'heiha.png',
    asset: './heiha.png',
  },
  {
    name: '[/加好友]',
    index: 97,
    path: 'jiahaoyou.png',
    asset: './jiahaoyou.png',
  },
  {
    name: '[/惊恐]',
    index: 98,
    path: 'jingkong.png',
    asset: './jingkong.png',
  },
  {
    name: '[/惊讶]',
    index: 99,
    path: 'jingya.png',
    asset: './jingya.png',
  },
  {
    name: '[/囧]',
    index: 100,
    path: 'jiong.png',
    asset: './jiong.png',
  },
  {
    name: '[/难过]',
    index: 101,
    path: 'nanguo.png',
    asset: './nanguo.png',
  },
  {
    name: '[/斜眼]',
    index: 102,
    path: 'xieyan.png',
    asset: './xieyan.png',
  },
  {
    name: '[/阴险]',
    index: 103,
    path: 'yinxian.png',
    asset: './yinxian.png',
  },
  {
    name: '[/悠闲]',
    index: 104,
    path: 'youxian.png',
    asset: './youxian.png',
  },
  {
    name: '[/咒骂]',
    index: 105,
    path: 'zhouma.png',
    asset: './zhouma.png',
  },
  {
    name: '[/比心]',
    index: 106,
    path: 'bixin.png',
    asset: './bixin.png',
  },
  {
    name: '[/强壮]',
    index: 107,
    path: 'jiayou.png',
    asset: './jiayou.png',
  },
  {
    name: '[/碰拳]',
    index: 108,
    path: 'pengquan.png',
    asset: './pengquan.png',
  },
  { name: '[/OK]', index: 109, path: 'ok.png', asset: './ok.png' },
  {
    name: '[/击掌]',
    index: 110,
    path: 'jizhang.png',
    asset: './jizhang.png',
  },
  {
    name: '[/左上]',
    index: 111,
    path: 'zuoshang.png',
    asset: './zuoshang.png',
  },
  {
    name: '[/握手]',
    index: 112,
    path: 'woshou.png',
    asset: './woshou.png',
  },
  {
    name: '[/抱拳]',
    index: 113,
    path: 'baoquan.png',
    asset: './baoquan.png',
  },
  {
    name: '[/勾引]',
    index: 114,
    path: 'gouyin.png',
    asset: './gouyin.png',
  },
  {
    name: '[/拳头]',
    index: 115,
    path: 'quantou.png',
    asset: './quantou.png',
  },
  { name: '[/弱]', index: 116, path: 'ruo.png', asset: './ruo.png' },
  {
    name: '[/胜利]',
    index: 117,
    path: 'shengli.png',
    asset: './shengli.png',
  },
  {
    name: '[/右边]',
    index: 118,
    path: 'youbian.png',
    asset: './youbian.png',
  },
  {
    name: '[/左边]',
    index: 119,
    path: 'zuobian.png',
    asset: './zuobian.png',
  },
  {
    name: '[/嘴唇]',
    index: 120,
    path: 'kiss.png',
    asset: './kiss.png',
  },
  {
    name: '[/爱心]',
    index: 121,
    path: 'xin.png',
    asset: './xin.png',
  },
  {
    name: '[/心碎]',
    index: 122,
    path: 'shangxin.png',
    asset: './shangxin.png',
  },
  {
    name: '[/玫瑰]',
    index: 123,
    path: 'meigui.png',
    asset: './meigui.png',
  },
  {
    name: '[/凋谢]',
    index: 124,
    path: 'diaoxie.png',
    asset: './diaoxie.png',
  },
  {
    name: '[/啤酒]',
    index: 125,
    path: 'pijiu.png',
    asset: './pijiu.png',
  },
  {
    name: '[/咖啡]',
    index: 126,
    path: 'kafei.png',
    asset: './kafei.png',
  },
  {
    name: '[/蛋糕]',
    index: 127,
    path: 'dangao.png',
    asset: './dangao.png',
  },
  {
    name: '[/礼物]',
    index: 128,
    path: 'liwu.png',
    asset: './liwu.png',
  },
  {
    name: '[/撒花]',
    index: 129,
    path: 'sahua.png',
    asset: './sahua.png',
  },
  { name: '[/V5]', index: 130, path: 'V5.png', asset: './V5.png' },
  { name: '[/绝]', index: 131, path: 'jue.png', asset: './jue.png' },
  { name: '[/666]', index: 132, path: '666.png', asset: './666.png' },
  {
    name: '[/给力]',
    index: 133,
    path: 'geili.png',
    asset: './geili.png',
  },
  {
    name: '[/红包]',
    index: 134,
    path: 'hongbao.png',
    asset: './hongbao.png',
  },
  { name: '[/屎]', index: 135, path: 'shi.png', asset: './shi.png' },
  { name: '[/发]', index: 136, path: 'fa.png', asset: './fa.png' },
  {
    name: '[/我太难了]',
    index: 137,
    path: 'wotainanle.png',
    asset: './wotainanle.png',
  },
  {
    name: '[/18禁]',
    index: 138,
    path: '18jin.png',
    asset: './18jin.png',
  },
  {
    name: '[/炸弹]',
    index: 139,
    path: 'zhadan.png',
    asset: './zhadan.png',
  },
  {
    name: '[/去污粉]',
    index: 140,
    path: 'quwufen.png',
    asset: './quwufen.png',
  },
  {
    name: '[/西瓜]',
    index: 141,
    path: 'xigua.png',
    asset: './xigua.png',
  },
  {
    name: '[/加鸡腿]',
    index: 142,
    path: 'jiajitui.png',
    asset: './jiajitui.png',
  },
  {
    name: '[/我酸了]',
    index: 143,
    path: 'wosuanle.png',
    asset: './wosuanle.png',
  },
  {
    name: '[/握爪]',
    index: 144,
    path: 'wozhua.png',
    asset: './wozhua.png',
  },
  {
    name: '[/太阳]',
    index: 145,
    path: 'taiyang.png',
    asset: './taiyang.png',
  },
  {
    name: '[/月亮]',
    index: 146,
    path: 'yueliang.png',
    asset: './yueliang.png',
  },
  {
    name: '[/给跪了]',
    index: 147,
    path: 'geiguile.png',
    asset: './geiguile.png',
  },
  {
    name: '[/蕉绿]',
    index: 148,
    path: 'jiaolv.png',
    asset: './jiaolv.png',
  },
  {
    name: '[/扎心]',
    index: 149,
    path: 'zhaxin.png',
    asset: './zhaxin.png',
  },
  {
    name: '[/胡瓜]',
    index: 150,
    path: 'hugua.png',
    asset: './hugua.png',
  },
  {
    name: '[/yyds]',
    index: 151,
    path: 'yyds.png',
    asset: './yyds.png',
  },
  { name: '[/emo]', index: 152, path: 'emo.png', asset: './emo.png' },
  {
    name: '[/开心兔]',
    index: 153,
    path: 'kaixintu.png',
    asset: './kaixintu.png',
  },
  {
    name: '[/招财兔]',
    index: 154,
    path: 'zhaocaitu.png',
    asset: './zhaocaitu.png',
  },
  {
    name: '[/年兽兔]',
    index: 155,
    path: 'nianshoutu.png',
    asset: './nianshoutu.png',
  },
  {
    name: '[/打call]',
    index: 156,
    path: 'dacall.png',
    asset: './dacall.png',
  },
  {
    name: '[/栓Q]',
    index: 157,
    path: 'shuanq.png',
    asset: './shuanq.png',
  },
  {
    name: '[/无语]',
    index: 158,
    path: 'wuyu.png',
    asset: './wuyu.png',
  },
  {
    name: '[/雪人]',
    index: 159,
    path: 'xueren.png',
    asset: './xueren.png',
  },
  {
    name: '[/雪花]',
    index: 160,
    path: 'xuehua.png',
    asset: './xuehua.png',
  },
  {
    name: '[/圣诞树]',
    index: 161,
    path: 'shengdanshu.png',
    asset: './shengdanshu.png',
  },
  {
    name: '[/平安果]',
    index: 162,
    path: 'pinganguo.png',
    asset: './pinganguo.png',
  },
  {
    name: '[/圣诞帽]',
    index: 163,
    path: 'shengdanmao.png',
    asset: './shengdanmao.png',
  },
  {
    name: '[/气球]',
    index: 164,
    path: 'qiqiu.png',
    asset: './qiqiu.png',
  },
  {
    name: '[/干杯]',
    index: 165,
    path: 'ganbei.png',
    asset: './ganbei.png',
  },
  {
    name: '[/烟花]',
    index: 166,
    path: 'yanhua.png',
    asset: './yanhua.png',
  },
  { name: '[/福]', index: 167, path: 'fu.png', asset: './fu.png' },
  {
    name: '[/candy]',
    index: 168,
    path: 'candy.png',
    asset: './candy.png',
  },
  {
    name: '[/糖葫芦]',
    index: 169,
    path: 'tanghulu.png',
    asset: './tanghulu.png',
  },
  {
    name: '[/虎头]',
    index: 170,
    path: 'hutou.png',
    asset: './hutou.png',
  },
  {
    name: '[/饺子]',
    index: 171,
    path: 'jiaozi.png',
    asset: './jiaozi.png',
  },
  {
    name: '[/鞭炮]',
    index: 172,
    path: 'bianpao.png',
    asset: './bianpao.png',
  },
  {
    name: '[/元宝]',
    index: 173,
    path: 'yuanbao.png',
    asset: './yuanbao.png',
  },
  {
    name: '[/灯笼]',
    index: 174,
    path: 'denglong.png',
    asset: './denglong.png',
  },
  {
    name: '[/锦鲤]',
    index: 175,
    path: 'jinli.png',
    asset: './jinli.png',
  },
  {
    name: '[/巧克力]',
    index: 176,
    path: 'qiaokeli.png',
    asset: './qiaokeli.png',
  },
  {
    name: '[/汤圆]',
    index: 177,
    path: 'tangyuan.png',
    asset: './tangyuan.png',
  },
  {
    name: '[/情书]',
    index: 178,
    path: 'qingshu.png',
    asset: './qingshu.png',
  },
  {
    name: '[/iloveyou]',
    index: 179,
    path: 'iloveyou.png',
    asset: './iloveyou.png',
  },
  {
    name: '[/戒指]',
    index: 180,
    path: 'jiezhi.png',
    asset: './jiezhi.png',
  },
  {
    name: '[/派对]',
    index: 181,
    path: 'sahua.png',
    asset: './sahua.png',
  },
  {
    name: '[/象]',
    index: 182,
    path: 'xiang.png',
    asset: './xiang.png',
  },
]
